name: Test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # We don't expect any OS specific behavior, but let's just test more to
        # be on the safe side.
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: miri
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: Install cargo-nextest
      run: |
        cargo install cargo-nextest
    - name: Run tests x86_64-unknown-linux-gnu (little-endian)
      run: |
        cargo miri nextest run --verbose --target x86_64-unknown-linux-gnu -j${{ steps.cpu-cores.outputs.count }}
    - name: Run tests mips64-unknown-linux-gnuabi64 (big-endian)
      run: |
        cargo miri nextest run --verbose --target mips64-unknown-linux-gnuabi64 -j${{ steps.cpu-cores.outputs.count }}  
  asan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Run tests 
      run: bash -c "for i in {0..100}; do RUSTFLAGS=-Zsanitizer=address cargo test --no-default-features --release; done"
    - name: Run tests with large test sizes
      run: bash -c "for i in {0..2}; do RUSTFLAGS=-Zsanitizer=address cargo test --release; done"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt
    - name: Check rustfmt
      run: cargo fmt --check
      # TODO clippy?
