name: Test

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  debug:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # We don't expect any OS specific behavior, but let's just test more to
        # be on the safe side.
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            # components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: miri
    - name: Run tests x86_64-unknown-linux-gnu
      run: |
        cargo miri test --verbose --target x86_64-unknown-linux-gnu
    - name: Run tests mips64-unknown-linux-gnuabi64
      run: |
        cargo miri test --verbose --target mips64-unknown-linux-gnuabi64
  
  asan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
    - name: Build
      run: RUSTFLAGS=-Zsanitizer=address cargo build --release
    - name: Run tests (TODO loop)
      run: RUSTFLAGS=-Zsanitizer=address cargo test --release

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt
    - name: Check rustfmt
      run: cargo fmt --check
      # TODO clippy?
